const logEvents = {};


const errorEvents = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_OR_PASSWORD_ERROR: 'USER_OR_PASSWORD_ERROR',

  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  TIME_CONFLICT: 'TIME_CONFLICT',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKINT_NOT_FOUND: 'BOOKING_NOT_FOUND',
  BOOKING_CANCEL_FORBIDDEN: 'BOOKING_CANCEL_FORBIDDEN',
  BOOKING_ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  BOOKING_UPDATE_FORBIDDEN: 'BOOKING_UPDATE_FORBIDDEN',

  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_INVALID: 'TOKEN_INVALID',
  JWT_SECRET_NOT_CONFIGURED: 'JWT_SECRET_NOT_CONFIGURED',
  ROLE_FORBIDDEN: 'ROLE_FORBIDDEN',
}


export {logEvents, errorEvents};
