services:
  mysql:
    image: mysql:8
    container_name: db_meeting_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_BASE}
    ports:
      - "3306:3306"                  # 宿主机:容器
    volumes:
      - meeting-mysql-data:/var/lib/mysql   # 数据持久化（named volume）
      - ./sql:/docker-entrypoint-initdb.d/
    restart: unless-stopped

volumes:
  meeting-mysql-data: