/** 演示用 append-only event log（报表 / 回放共用） */
window.DEMO_SESSION = {
  sessionId: 'sess_demo_8f3a',
  userId: 'user_42',
  startedAt: '2026-05-10T14:02:11.000Z',
  model: 'deepseek-v4-flash',
  provider: 'deepseek',
};

window.DEMO_LOG = [
  {
    eventId: 'evt_001',
    seq: 1,
    schemaVersion: 1,
    at: '2026-05-10T14:02:11.120Z',
    type: 'input',
    text: '帮我看一下 expressjs-bookstore 里 agent 的测试能不能跑过，跑不过就修。',
    source: 'user',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 0,
      actor: 'user',
      channel: 'cli',
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_002',
    seq: 2,
    at: '2026-05-10T14:02:13.450Z',
    type: 'thought',
    text: '需要先了解项目结构，列出 agent 目录并读取 package.json 里的 test 脚本。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 1,
      model: 'deepseek-v4-flash',
      provider: 'deepseek',
      latencyMs: 2310,
      usage: { promptTokens: 412, completionTokens: 89 },
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_003',
    seq: 3,
    at: '2026-05-10T14:02:13.520Z',
    type: 'action',
    id: 'call_list_01',
    name: 'list_files',
    args: { path: 'agent', pattern: '**/*' },
    meta: { roundId: 'round_9a1b2c3d', turn: 1, traceId: 'trace_7f8e9d0c' },
  },
  {
    eventId: 'evt_004',
    seq: 4,
    at: '2026-05-10T14:02:13.890Z',
    type: 'observation',
    id: 'call_list_01',
    name: 'list_files',
    isError: false,
    result:
      'src/agent/agentLoop.ts\nsrc/agent/session.ts\nsrc/agent/store.ts\npackage.json\nvitest.config.ts\n...',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 1,
      latencyMs: 370,
      resultBytes: 1240,
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_005',
    seq: 5,
    at: '2026-05-10T14:02:16.100Z',
    type: 'thought',
    text: '运行 pnpm test，确认失败用例。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 2,
      model: 'deepseek-v4-flash',
      latencyMs: 1980,
      usage: { promptTokens: 890, completionTokens: 42 },
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_006',
    seq: 6,
    at: '2026-05-10T14:02:16.180Z',
    type: 'action',
    id: 'call_shell_02',
    name: 'run_terminal',
    args: { command: 'cd agent && pnpm test', cwd: '/Users/dev/expressjs-bookstore' },
    meta: { roundId: 'round_9a1b2c3d', turn: 2, traceId: 'trace_7f8e9d0c' },
  },
  {
    eventId: 'evt_007',
    seq: 7,
    at: '2026-05-10T14:02:22.400Z',
    type: 'observation',
    id: 'call_shell_02',
    name: 'run_terminal',
    isError: true,
    result: 'FAIL session.test.ts > persist order\nENOENT test-session.jsonl',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 2,
      latencyMs: 6220,
      exitCode: 1,
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_008',
    seq: 8,
    at: '2026-05-10T14:02:25.800Z',
    type: 'thought',
    text: '失败是 store 竞态：handleAgentEvent 未 await。应改为串行 append 或 SessionLog 单出口。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 3,
      model: 'deepseek-v4-flash',
      latencyMs: 3100,
      usage: { promptTokens: 1102, completionTokens: 156 },
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_009',
    seq: 9,
    at: '2026-05-10T14:02:26.050Z',
    type: 'action',
    id: 'call_read_03',
    name: 'read_file',
    args: { path: 'agent/src/agent/session.ts', offset: 105, limit: 20 },
    meta: { roundId: 'round_9a1b2c3d', turn: 3, traceId: 'trace_7f8e9d0c' },
  },
  {
    eventId: 'evt_010',
    seq: 10,
    at: '2026-05-10T14:02:26.320Z',
    type: 'observation',
    id: 'call_read_03',
    name: 'read_file',
    isError: false,
    result: 'void this.handleAgentEvent(event); // fire-and-forget',
    meta: { roundId: 'round_9a1b2c3d', turn: 3, latencyMs: 270, traceId: 'trace_7f8e9d0c' },
  },
  {
    eventId: 'evt_011',
    seq: 11,
    at: '2026-05-10T14:02:31.500Z',
    type: 'output',
    text: '测试失败原因：Session 异步写 store 导致竞态。建议统一 SessionLog.append 并 await。\n\n已定位代码：session.ts handleAgentEvent 使用 void。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 3,
      model: 'deepseek-v4-flash',
      latencyMs: 5180,
      usage: { promptTokens: 1450, completionTokens: 198 },
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_012',
    seq: 12,
    at: '2026-05-10T14:05:00.000Z',
    type: 'summary',
    text: '[系统摘要] 上一轮 round_9a1b2c3d：用户请求修 agent 测试；agent 调用 list_files、run_terminal(失败)、read_file；结论为 store 写入竞态。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 0,
      compressedFromSeq: [1, 11],
      actor: 'system',
      reason: 'context_window_policy',
      traceId: 'trace_7f8e9d0c',
    },
  },
  {
    eventId: 'evt_013',
    seq: 13,
    at: '2026-05-10T14:05:02.100Z',
    type: 'input',
    text: '按你说的改，并再跑一遍测试。',
    source: 'user',
    meta: {
      roundId: 'round_e4f5g6h7',
      turn: 0,
      actor: 'user',
      channel: 'cli',
      traceId: 'trace_a1b2c3d4',
    },
  },
  {
    eventId: 'evt_014',
    seq: 14,
    at: '2026-05-10T14:05:08.200Z',
    type: 'thought',
    text: '实现 SessionLog 单出口，session 只订阅 append。',
    meta: {
      roundId: 'round_e4f5g6h7',
      turn: 1,
      model: 'deepseek-v4-flash',
      latencyMs: 4100,
      usage: { promptTokens: 620, completionTokens: 72 },
      traceId: 'trace_a1b2c3d4',
    },
  },
  {
    eventId: 'evt_015',
    seq: 15,
    at: '2026-05-10T14:05:14.600Z',
    type: 'action',
    id: 'call_shell_04',
    name: 'run_terminal',
    args: { command: 'cd agent && pnpm test' },
    meta: { roundId: 'round_e4f5g6h7', turn: 1, traceId: 'trace_a1b2c3d4' },
  },
  {
    eventId: 'evt_016',
    seq: 16,
    at: '2026-05-10T14:05:20.100Z',
    type: 'observation',
    id: 'call_shell_04',
    name: 'run_terminal',
    isError: false,
    result: 'Test Files  3 passed (3)\nTests  21 passed (21)',
    meta: {
      roundId: 'round_e4f5g6h7',
      turn: 1,
      latencyMs: 5500,
      exitCode: 0,
      traceId: 'trace_a1b2c3d4',
    },
  },
  {
    eventId: 'evt_017',
    seq: 17,
    at: '2026-05-10T14:05:22.300Z',
    type: 'output',
    text: '已统一 append 出口，21 个测试全部通过。',
    meta: {
      roundId: 'round_e4f5g6h7',
      turn: 1,
      model: 'deepseek-v4-flash',
      usage: { promptTokens: 980, completionTokens: 45 },
      traceId: 'trace_a1b2c3d4',
    },
  },
];

window.DEMO_TYPE_COLORS = {
  input: '#22c55e',
  thought: '#a78bfa',
  action: '#f59e0b',
  observation: '#06b6d4',
  output: '#34d399',
  summary: '#64748b',
  agent_error: '#ef4444',
};

/** Eval：同一用户问题，另一次 run（首轮即修好测试，更短、更省 token） */
window.DEMO_LOG_RUN_B = [
  window.DEMO_LOG[0],
  {
    eventId: 'evt_b02',
    seq: 2,
    at: '2026-05-10T15:10:01.000Z',
    type: 'thought',
    text: '直接检查 session 持久化逻辑并修复竞态。',
    meta: {
      roundId: 'round_run_b_01',
      turn: 1,
      model: 'deepseek-v4-flash',
      latencyMs: 1800,
      usage: { promptTokens: 400, completionTokens: 55 },
      traceId: 'trace_run_b',
    },
  },
  {
    eventId: 'evt_b03',
    seq: 3,
    at: '2026-05-10T15:10:02.000Z',
    type: 'action',
    id: 'call_patch',
    name: 'apply_patch',
    args: { path: 'agent/src/agent/session.ts' },
    meta: { roundId: 'round_run_b_01', turn: 1, traceId: 'trace_run_b' },
  },
  {
    eventId: 'evt_b04',
    seq: 4,
    at: '2026-05-10T15:10:03.500Z',
    type: 'observation',
    id: 'call_patch',
    name: 'apply_patch',
    isError: false,
    result: 'patch applied: await handleAgentEvent',
    meta: { roundId: 'round_run_b_01', turn: 1, latencyMs: 1500, traceId: 'trace_run_b' },
  },
  {
    eventId: 'evt_b05',
    seq: 5,
    at: '2026-05-10T15:10:08.000Z',
    type: 'action',
    id: 'call_test',
    name: 'run_terminal',
    args: { command: 'cd agent && pnpm test' },
    meta: { roundId: 'round_run_b_01', turn: 1, traceId: 'trace_run_b' },
  },
  {
    eventId: 'evt_b06',
    seq: 6,
    at: '2026-05-10T15:10:14.000Z',
    type: 'observation',
    id: 'call_test',
    name: 'run_terminal',
    isError: false,
    result: 'Tests 21 passed',
    meta: { roundId: 'round_run_b_01', turn: 1, latencyMs: 6000, exitCode: 0, traceId: 'trace_run_b' },
  },
  {
    eventId: 'evt_b07',
    seq: 7,
    at: '2026-05-10T15:10:16.000Z',
    type: 'output',
    text: '已修复 SessionLog 串行写入，测试全部通过。',
    meta: {
      roundId: 'round_run_b_01',
      turn: 1,
      usage: { promptTokens: 900, completionTokens: 40 },
      traceId: 'trace_run_b',
    },
  },
];

/** 分支：在 seq 11 后用户选择「不继续修」的平行时间线 */
window.DEMO_LOG_BRANCH_ALT = window.DEMO_LOG.filter((e) => e.seq <= 10).concat([
  {
    eventId: 'evt_alt_11',
    seq: 11,
    at: '2026-05-10T14:02:31.500Z',
    type: 'output',
    text: '定位到 store 竞态，但当前权限无法改代码。建议人工处理或新建分支。',
    meta: {
      roundId: 'round_9a1b2c3d',
      turn: 3,
      model: 'deepseek-v4-flash',
      traceId: 'trace_7f8e9d0c',
    },
  },
]);

/** Human-in-the-loop：待审批的 action（尚未 append observation） */
window.DEMO_PENDING_APPROVAL = {
  eventId: 'evt_pending',
  seq: 18,
  at: '2026-05-10T16:00:00.000Z',
  type: 'action',
  id: 'call_rm',
  name: 'run_terminal',
  args: { command: 'rm -rf ./tmp/cache' },
  meta: {
    roundId: 'round_e4f5g6h7',
    turn: 2,
    requiresApproval: true,
    requestedBy: 'agent',
    traceId: 'trace_a1b2c3d4',
  },
};
