name: CI DEMO

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print Hello CI/C
        run: echo "Hello CI/CD"
