name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test:ci

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{
          secrets.DOCKERHUB_USERNAME }}" --password-stdin
     
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/meeting-backend:latest .
      
      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/meeting-backend:latest
